In [1]:
import numpy as np
from MCEq.core import MCEqRun
import crflux.models as pm
from utils.helpers import *

In [2]:
path = '/data/user/khymon/cs-analysis/'

In [3]:
numu_untuned = np.load(path + 'numu_1.0pion_1.0kaon_10000.0_const_mceqflux.npy')

In [4]:
numu_tuned = np.load(path + 'numu_1.5pion_0.8kaon_10000.0_const_mceqflux.npy')

In [5]:
numu_tuned[0,50,50:]/numu_untuned[0,5,50:] 

array([0.96200982, 0.98018502, 0.98441987, 0.98822356, 0.99165313,
       0.99479427, 0.99764263, 1.00027333, 1.00281555, 1.00523597,
       1.0075731 , 1.0098126 , 1.01191353, 1.01396526, 1.01597902,
       1.0178684 , 1.01957222, 1.02100134, 1.02204977, 1.02269439,
       1.02297315, 1.02287167, 1.02238385, 1.02143792, 1.0201176 ,
       1.01861906, 1.01686874, 1.0150061 , 1.01328825, 1.01175694,
       1.01048334, 1.00956599, 1.009048  , 1.00896534, 1.00935414,
       1.01010449, 1.01118685, 1.01253859, 1.01412937, 1.0159219 ,
       1.01788842, 1.01993431, 1.02210907, 1.02429485, 1.02652329,
       1.02849053, 1.03050206, 1.03212551, 1.03330704, 1.03354805,
       1.03226113, 1.03002193, 1.02715175, 1.0234928 , 1.01910657,
       1.01377325, 1.01003479, 1.00792317, 1.00545622, 1.00402023,
       1.0040296 , 1.00262593, 1.00356318, 1.00429803, 1.00510499,
       1.00462885, 1.01207686, 1.027155  , 1.0533005 , 1.07862296,
       1.08099076])

In [6]:
annualavg = numu_untuned[0].mean(axis=0)

In [7]:
numu_untuned[0][3]/annualavg

array([1.00089143, 1.00082847, 1.00078278, 1.00082487, 1.00075303,
       1.00065705, 1.00059192, 1.00060223, 1.00064372, 1.00074083,
       1.00090953, 1.00118497, 1.00159129, 1.00213716, 1.00283275,
       1.00376313, 1.00500465, 1.00646614, 1.00818851, 1.01009488,
       1.01210806, 1.01412748, 1.01603271, 1.01771411, 1.01911115,
       1.02022734, 1.02113959, 1.021958  , 1.02283469, 1.02392089,
       1.02520187, 1.02670088, 1.02843838, 1.03036266, 1.03238648,
       1.03439502, 1.03625754, 1.03786311, 1.03917159, 1.04018615,
       1.04098549, 1.04171446, 1.04252619, 1.0435783 , 1.04501206,
       1.04691379, 1.04931229, 1.05213752, 1.05528347, 1.05861523,
       1.06197821, 1.06522031, 1.06823362, 1.07092458, 1.07323564,
       1.07515201, 1.07667594, 1.07782872, 1.07862363, 1.07908861,
       1.07924949, 1.07912801, 1.0787455 , 1.07810164, 1.07723197,
       1.07613074, 1.07476156, 1.07310876, 1.07119676, 1.06895896,
       1.06624909, 1.06301695, 1.05931642, 1.0550904 , 1.05035

In [30]:
def get_sv_amplitude(flux, energy, ebins, angles_edges, doys):
        masks = []
        flux_year = np.mean(flux, axis=1)

        sv_amplitude = np.ndarray(shape=(len(angles_edges) - 1, len(ebins), len(doys)), dtype=float)
       
        
        for j in range(3 - 1):
            for i in range(len(ebins) - 1):
                mask = (energy >= ebins[i]) & (energy < ebins[i + 1])
                print(mask)
                masks.append(mask)
                sv_amplitude[j][i] = np.sum(flux[j, :, mask], axis=0) / np.sum(flux_year[j, mask]) 
                
            print('after',sv_amplitude[0])

            return sv_amplitude


In [ ]:
step = 0.3
bins = np.logspace(2.1, 6., num=int((6. - 2.1) / step) + 1)

In [10]:
mceq = MCEqRun(
            interaction_model="SIBYLL2.3c",
            theta_deg=0.0,
            primary_model=(pm.HillasGaisser2012, "H3a"),
        )

energy = mceq.e_grid

MCEqRun::set_interaction_model(): SIBYLL23C
ParticleManager::_init_default_tracking(): Initializing default tracking categories (pi, K, mu)
MCEqRun::set_density_model(): Setting density profile to CORSIKA ('BK_USStd', None)
MCEqRun::set_primary_model(): HillasGaisser2012 H3a


In [11]:
doy = doys(5)

In [31]:
ampl = get_sv_amplitude(numu_untuned, energy, bins,[1,1,1], doy)

[False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False  True  True  True False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False]
[False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False  True
  True  True False False False False False 

In [29]:
ampl[0][11]

array([1.08081575, 1.07974308, 1.07797789, 1.07548786, 1.07225548,
       1.06827902, 1.06357274, 1.05816633, 1.05210378, 1.04544168,
       1.03824747, 1.03059742, 1.02257486, 1.01426833, 1.00576997,
       0.99717396, 0.98857493, 0.98006641, 0.97173909, 0.96367907,
       0.95596615, 0.94867267, 0.94186264, 0.93559152, 0.92990621,
       0.92484555, 0.92044089, 0.91671692, 0.91369238, 0.91138082,
       0.90979122, 0.90892851, 0.90879382, 0.90938474, 0.9106952 ,
       0.91271528, 0.91543073, 0.91882245, 0.92286569, 0.92752932,
       0.93277509, 0.93855687, 0.94482025, 0.95150225, 0.95853152,
       0.96582901, 0.97330919, 0.98088203, 0.98845552, 0.99593884,
       1.00324582, 1.01029851, 1.01703048, 1.02338949, 1.02933946,
       1.03486143, 1.03995359, 1.04463011, 1.04891868, 1.05285693,
       1.05648774, 1.05985414, 1.06299416, 1.06593633, 1.06869609,
       1.07127368, 1.07365337, 1.07580402, 1.07768082, 1.07922797,
       1.080382  , 1.08107554, 1.08124127])

In [13]:
np.sum(numu_untuned[0][:][12:17],axis=2).shape

AxisError: axis 2 is out of bounds for array of dimension 2

In [ ]:
numu_untuned.shape

(3, 73, 121)

In [ ]:
numu_untuned[0][[12:17].shape

(5, 121)

In [ ]:
numu_untuned[0,:,12:17].shape

(73, 5)

In [ ]:
np.sum(numu_untuned[0,:,12:17],axis=1).shape

(73,)