In [1]:
import matplotlib.pyplot as plt
from matplotlib import cm
from matplotlib.colors import Normalize
import matplotlib.lines as mlines
from scipy.interpolate import UnivariateSpline
from tqdm import tqdm
import pickle
import numpy as np

import crflux.models as pm

from MCEq.data import InteractionCrossSections
from MCEq.core import MCEqRun
import  mceq_underground_helper_forsplines as helper

In [2]:
plot_dir = '/hetghome/khymon/Plots/cs-analysis/'


In [4]:
p1_values = [0.00, 0.05, -0.05, 0.00,  0.00, 0.00, 0.00]
p2_values = [0.00, 0.00,  0.00, 0.05, -0.05, 0.00, 0.00]
p3_values = [0.00, 0.00,  0.00, 0.00,  0.00, 0.05, -0.05]
season_values = ["jan", "apr", "jul"]  #  seasons



helper.initialize_flux_dicts(p1_values, p2_values, p3_values)
helper.some_function_that_uses_angles()
angles = helper.angles

Key: (0.0, 0.0, 0.0)
Length of cos_thetas: 3
Shape of flux for season jan: (3, 121)
Shape of flux for season apr: (3, 121)
Shape of flux for season jul: (3, 121)
Key: (0.05, 0.0, 0.0)
Length of cos_thetas: 3
Shape of flux for season jan: (3, 121)
Shape of flux for season apr: (3, 121)
Shape of flux for season jul: (3, 121)
Key: (-0.05, 0.0, 0.0)
Length of cos_thetas: 3
Shape of flux for season jan: (3, 121)
Shape of flux for season apr: (3, 121)
Shape of flux for season jul: (3, 121)
Key: (0.0, 0.05, 0.0)
Length of cos_thetas: 3
Shape of flux for season jan: (3, 121)
Shape of flux for season apr: (3, 121)
Shape of flux for season jul: (3, 121)
Key: (0.0, -0.05, 0.0)
Length of cos_thetas: 3
Shape of flux for season jan: (3, 121)
Shape of flux for season apr: (3, 121)
Shape of flux for season jul: (3, 121)
Key: (0.0, 0.0, 0.05)
Length of cos_thetas: 3
Shape of flux for season jan: (3, 121)
Shape of flux for season apr: (3, 121)
Shape of flux for season jul: (3, 121)
Key: (0.0, 0.0, -0.05

/hetghome/khymon/cs-analysis/IceCube_diffuse_underground_bundles/mceq_underground_helper_forsplines.py:99: RuntimeWarning: invalid value encountered in arccos
  angles = np.degrees(np.arccos(cos_thetas))  # Convert from cos(theta) to theta in degrees


In [6]:
helper._flux(0.0, "apr", p1=0.00, p2=0.0, p3= 0.0, iecr=None)

array([1.16221386e-03, 1.26948600e-03, 1.37648682e-03, 1.47533340e-03,
       1.56335171e-03, 1.63697377e-03, 1.69103554e-03, 1.71586308e-03,
       1.70739559e-03, 1.65842163e-03, 1.56579094e-03, 1.42995871e-03,
       1.25901264e-03, 1.06446070e-03, 8.63796219e-04, 6.71553727e-04,
       4.99745300e-04, 3.55133596e-04, 2.41991368e-04, 1.59772118e-04,
       1.03431098e-04, 6.51157394e-05, 3.93373761e-05, 2.32682012e-05,
       1.33668954e-05, 7.49599241e-06, 4.11243537e-06, 2.21388483e-06,
       1.17112315e-06, 6.08657715e-07, 3.10967470e-07, 1.56383487e-07,
       7.71879775e-08, 3.74479816e-08, 1.79276123e-08, 8.47808808e-09,
       3.96721350e-09, 1.83887930e-09, 8.44858727e-10, 3.85022216e-10,
       1.74253120e-10, 7.83848788e-11, 3.50440894e-11, 1.55843998e-11,
       6.89856789e-12, 3.04077721e-12, 1.33403645e-12, 5.82675859e-13,
       2.53499695e-13, 1.09852713e-13, 4.74637504e-14, 2.04349799e-14,
       8.76824285e-15, 3.75206705e-15, 1.60050908e-15, 6.80035647e-16,
      

In [7]:
def derivative(param,angle):
    if param =='p1':
        delta_phi = helper._flux(angle, "apr", p1=0.05, p2=0.0, p3=0.0, iecr=None) - helper._flux(angle, "apr", p1=-0.05, p2=0.0, p3= 0.0, iecr=None)
    elif param =='p2':
        delta_phi = helper._flux(angle, "apr", p1=0.0, p2=0.05, p3=0.0, iecr=None) - helper._flux(angle, "apr", p1=0.0, p2=-0.05, p3= 0.0, iecr=None)
    elif param =='p3':
        delta_phi = helper._flux(angle, "apr", p1=0.0, p2=0.0, p3=0.05, iecr=None) - helper._flux(angle, "apr", p1=0.0, p2=0.0, p3= -0.05, iecr=None)

    return delta_phi/(2*0.05)

In [8]:
angles

array([90., nan, nan])

In [9]:
thetas = np.array([0., 30., 60.])
cos_thetas = np.cos(np.radians(thetas))

In [10]:
cos_thetas  

array([1.       , 0.8660254, 0.5      ])